# .pre-commit-config.yaml

default_stages: [commit]
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: fix-byte-order-marker
    - id: end-of-file-fixer
    - id: check-merge-conflict
    - id: check-symlinks
    - id: debug-statements
    - id: mixed-line-ending
    - id: requirements-txt-fixer
    - id: check-added-large-files
    - id: detect-private-key
    - id: trailing-whitespace

# isort
- repo: https://github.com/asottile/seed-isort-config
  rev: v2.2.0
  hooks:
    - id: seed-isort-config

# black
- repo: https://github.com/ambv/black
  rev: 22.10.0
  hooks:
    - id: black
      args:
        - --line-length=88
        - --include='\.pyi?$'
        - --exclude="""\.git |
          \.__pycache__|
          examples|
          env|
          dist"""

# flake8
- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
    - id: flake8
      additional_dependencies:
        - flake8-bugbear
        - flake8-implicit-str-concat
      args:
        - "--max-line-length=100"
        - "--select=B,C,E,F,W,T4,B9"
        - "--ignore=B006,B008,B010,B903,B907,W503"
        - "--builtins=F821, F405"
